apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  labels:
    app: postgres
data:
  POSTGRES_DB: _postgresqldb_
  POSTGRES_USER: _postgresqluser_
  POSTGRES_PASSWORD: _postgresqlpassword_
  POSTGRES_INITDB_ARGS: "-E UTF8 --locale=ja_JP.UTF-8 --lc-collate=ja_JP.UTF-8 --lc-ctype=ja_JP.UTF-8" 
